version: '3.8'

services:
  db: 
    container_name: db
    build: ./db
    image: db:1.1
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - green-basket

  backend:
    container_name: backend
    build: ./backend
    image: backend:1.1
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - green-basket

  frontend:
    container_name: frontend
    build: ./frontend
    image: frontend:1.1
    ports:
      - "5173:5173"
    networks:
      - green-basket

networks:
  green-basket: