# Generated by Django 4.2.6 on 2023-11-01 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.BigIntegerField()),
                ('payment_mode', models.CharField(max_length=50)),
                ('deliver_at', models.DateField()),
                ('delivery_status', models.CharField(max_length=50)),
                ('total_items', models.IntegerField(default=0)),
                ('delivered_name', models.CharField(max_length=100)),
                ('delivered_phone_number', models.BigIntegerField()),
                ('delivered_address', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_imageurl', models.CharField(max_length=1000)),
                ('ordered_brand', models.CharField(max_length=100)),
                ('ordered_details', models.CharField(max_length=200)),
                ('ordered_price', models.PositiveIntegerField()),
                ('product_quantity', models.PositiveIntegerField()),
                ('ordered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
