# Generated by Django 4.2.6 on 2023-10-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_details', models.CharField(max_length=200)),
                ('product_description', models.CharField(max_length=1000)),
                ('product_price', models.PositiveIntegerField()),
                ('product_category', models.CharField(max_length=100)),
                ('product_brand', models.CharField(max_length=100)),
                ('product_quantity', models.PositiveIntegerField()),
                ('product_imageurl', models.CharField(max_length=1000)),
            ],
        ),
    ]
